### ISSUE TITLE
Membership maintainance check

### ISSUE THREAD

**Issue by JohanMabille** [jupyter/kernels-team-compass#7]
Hi all,

One year has almost passed since the creation of this council and I wanted to trigger a [membership maintainance check](https://jupyter-foundations-and-standards.readthedocs.io/en/latest/team/becoming-member.html#membership-maintenance).

> Every six months, one currently active member should open an issue in the team-compass repo asking all currently active team members to reply if they still consider themselves active. If not (or no response is given by a team member), it will be assumed that they have gone inactive. This will help keep the active member list up-to-date.
>
> Remember, an inactive member can return at any time by simply changing their status on the team-compass page.

Please indicate below one way or the other if you would like to remain as an active member of this council, or if you prefer to become inactive at this time.

This poll will remain open until the **first week of January, 2024**, at which point we will assume an `inactive` role for anyone not participating.

- @Carreau wishes to ...
  - [x] remain active
  - [ ] become inactive
- @ccordoba12 wishes to ...
  - [x] remain active
  - [ ] become inactive
- @SylvainCorlay wishes to ...
  - [x] remain active
  - [ ] become inactive
- @afshin wishes to ...
  - [x] remain active
  - [ ] become inactive
- @jasongrout wishes to ...
  - [x] remain active
  - [ ] become inactive
- @ivanov wishes to ...
  - [x] remain active
  - [ ] become inactive
- @JohanMabille wishes to ...
  - [x] remain active
  - [ ] become inactive
- @fperez wishes to ...
  - [ ] remain active
  - [x] become inactive
- @minrk wishes to ...
  - [x] remain active
  - [ ] become inactive
- @blink1073 wishes to ...
  - [x] remain active
  - [ ] become inactive
- @willingc wishes to ...
  - [x] remain active
  - [ ] become inactive
- @Zsailer wishes to ...
  - [x] remain active
  - [ ] become inactive
- @kevin-bates wishes to ...
  - [x] remain active
  - [ ] become inactive

**Comment by Zsailer** [comment]
I'd like to remain active, but I don't have access to edit the top comment.

**Comment by kevin-bates** [comment]
Hi @JohanMabille - Thanks for handling this! I too would like to remain active but can't edit.

**Comment by ivanov** [comment]
@Zsailer and @kevin-bates I've checked the box for both of you, and also added the @jupyter/kernels-council to be an admin of this repo, so you should be able to edit yourselves from now on.

**Comment by ivanov** [comment]
Oh, and I now see that neither of you were on that @jupyter/kernels-council  list, so that's also now been corrected.

**Comment by davidbrochart** [comment]
I'd like to remain (or become) active, but I cannot see myself in the list. How can I join?

**Comment by JohanMabille** [comment]
> Oh, and I now see that neither of you were on that @jupyter/kernels-council list, so that's also now been corrected.

Shame on me!

EDIT: actually it seems I cannot add anyone to that team. There is also a second [kernel council team](https://github.com/orgs/jupyter/teams/jupyterkernelconcil) which should probably be deleted.

**Comment by JohanMabille** [comment]
> I'd like to remain (or become) active, but I cannot see myself in the list. How can I join?

I'm sending you the invites (both on Github and the google mailing list)

**Comment by JohanMabille** [comment]
@ivanov can you invite David to the KernelCouncil list, or make me an admin of the team so that I can send invites?

**Comment by ivanov** [comment]
@davidbrochart wrote:
> I'd like to remain (or become) active, but I cannot see myself in the list. How can I join?

Thanks for your interest, David, [here's the relevant portion of the kernels team compass page about becoming a council member](https://kernels-team-compass.readthedocs.io/en/latest/team/becoming-member.html), you already have Johan as your champion so we will start that process internally.

@JohanMabille wrote:
> I'm sending you the invites (both on Github and the google mailing list
>@ivanov can you invite David to the KernelCouncil list, or make me an admin of the team so that I can send invites?

You should be able to manage that list now. However, I think we should follow the [Nominating a new member](https://kernels-team-compass.readthedocs.io/en/latest/team/becoming-member.html#nominating-a-new-member) process outlined on the team compass for adding new members. To that end, I will remove David from the membership check and the mailing list for the time being, until we  add him using the official process. (David, I look forward to having you join the kernels council, so please do not misinterpret my actions as opposition to your participation here).

> There is also a second [kernel council team](https://github.com/orgs/jupyter/teams/jupyterkernelconcil) which should probably be deleted.

Ah yes,  I suspect it was the `concil` -> `council` typo that made that one fly under the radar, I have edited its description so we do not use it. But from there I figured out that there were additional repositories that the council should have administration over (`jupyter_console` and `kernels`) so I added those.

**Comment by JohanMabille** [comment]
Fixed in #8

**Comment by fperez** [comment]
Sorry for the late reply, just catching up with backlog. But that's a signal I should go inactive, as realistically I can't keep up.
